<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Citi Bike Usage Analysis</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.5.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.5.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="report.html">Report</a>
</li>
<li>
  <a href="data.html">Data</a>
</li>
<li>
  <a href="eda.html">Exporatory Data Analysis</a>
</li>
<li>
  <a href="analysis.html">Analysis</a>
</li>
<li>
  <a href="https://github.com/chelsopp/citi-bike-usage-analysis">
    <span class="fa fa-youtube fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/chelsopp/citi-bike-usage-analysis">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Citi Bike Usage Analysis</h1>

</div>


<div
id="is-there-a-statistically-significant-difference-in-average-ride-duration-between-annual-members-and-casual-riders"
class="section level1">
<h1>Is there a statistically significant difference in average ride
duration between annual members and casual riders?</h1>
<pre class="r"><code>#T-test: Difference in ride duration between member types
casual_duration &lt;- citibike_nj_analysis %&gt;%
  filter(member_casual == &quot;casual&quot;) %&gt;%
  pull(ride_length_min)

member_duration &lt;- citibike_nj_analysis %&gt;%
  filter(member_casual == &quot;member&quot;) %&gt;%
  pull(ride_length_min)

ttest_result &lt;- t.test(casual_duration, member_duration, var.equal = FALSE)

cat(sprintf(&quot;  t = %.2f\n&quot;, ttest_result$statistic))</code></pre>
<pre><code>##   t = 88.63</code></pre>
<pre class="r"><code>cat(sprintf(&quot;  p-value = %s\n&quot;, 
            ifelse(ttest_result$p.value &lt; 0.001,
                   &quot;&lt; 0.001&quot;,
                   sprintf(&quot;%.4f&quot;, ttest_result$p.value))))</code></pre>
<pre><code>##   p-value = &lt; 0.001</code></pre>
<pre class="r"><code>cat(sprintf(&quot;  Mean difference: %.2f minutes\n&quot;,
            mean(casual_duration) - mean(member_duration)))</code></pre>
<pre><code>##   Mean difference: 8.68 minutes</code></pre>
<pre class="r"><code>cat(sprintf(&quot;  95%% CI: [%.2f, %.2f]\n&quot;,
            ttest_result$conf.int[1], ttest_result$conf.int[2]))</code></pre>
<pre><code>##   95% CI: [8.49, 8.87]</code></pre>
<p>The t-test indicates a highly significant difference in ride
durations between annual members and casual riders (p &lt; 0.001).
Casual riders consistently take longer trips, averaging 8.68 minutes
more than members. The narrow 95% confidence interval (8.49–8.87
minutes) reinforces the reliability of this gap, suggesting a clear
behavioral distinction: members use bikes for short, utilitarian trips,
while casual riders tend toward longer, more leisure-oriented rides.</p>
</div>
<div
id="is-there-an-association-between-a-riders-membership-type-and-whether-they-ride-on-a-weekday-or-weekend"
class="section level1">
<h1>Is there an association between a rider’s membership type and
whether they ride on a weekday or weekend?</h1>
<pre class="r"><code># Chi-square test: Association between member type and day type
member_day_table &lt;- citibike_nj_analysis %&gt;%
  count(member_casual, day_type) %&gt;%
  pivot_wider(names_from = member_casual, values_from = n, values_fill = 0) %&gt;%
  column_to_rownames(&quot;day_type&quot;)

chisq_test &lt;- chisq.test(as.matrix(member_day_table))

cat(sprintf(&quot;  X-squared = %.2f\n&quot;, chisq_test$statistic))</code></pre>
<pre><code>##   X-squared = 16403.81</code></pre>
<pre class="r"><code>cat(sprintf(&quot;  p-value = %s\n&quot;,
            ifelse(chisq_test$p.value &lt; 0.001,
                   &quot;&lt; 0.001&quot;,
                   sprintf(&quot;%.4f&quot;, chisq_test$p.value))))</code></pre>
<pre><code>##   p-value = &lt; 0.001</code></pre>
<p>The chi-square test identifies a strong and statistically significant
association between membership type and day type (weekday vs. weekend),
with a large test statistic (X² = 16,403.81, df = 1, p &lt; 0.001). This
means the distribution of rides across weekdays and weekends differs
meaningfully by rider type. Casual riders are far more active on
weekends, whereas annual members dominate weekday usage, supporting the
idea that members use the system for routine commuting, while casual
riders use it for recreational or occasional trips.</p>
</div>
<div
id="does-average-ride-duration-differ-significantly-across-the-four-seasons"
class="section level1">
<h1>Does average ride duration differ significantly across the four
seasons?</h1>
<pre class="r"><code># ANOVA: Ride duration across seasons
season_anova_data &lt;- citibike_nj_analysis %&gt;%
  filter(ride_length_min &lt;= outlier_bounds$upper)

season_anova &lt;- aov(ride_length_min ~ season, data = season_anova_data)
season_anova_summary &lt;- summary(season_anova)

print(season_anova_summary)</code></pre>
<pre><code>##                 Df   Sum Sq Mean Sq F value Pr(&gt;F)    
## season           3    52686   17562    1189 &lt;2e-16 ***
## Residuals   872179 12883626      15                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The ANOVA results show that ride duration varies significantly by
season (F = 1,189, df = 3, p &lt; 0.001). This means not all seasons
have the same average ride length—seasonal conditions likely influence
how long riders choose to stay on the bikes. These differences may
reflect weather patterns, tourism cycles, or seasonal variations in
recreational activity, all of which appear to meaningfully affect riding
behavior.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
