---
title: "Final Report"
output: 
  html_document:
    toc: true
    toc_float: true
---

## Motivation

## Initial Questions

## Data

#### Sources
We located and downloaded the publicly available Citi Bike Trip History Data via the [Citi Bike System Data portal](https://citibikenyc.com/system-data). This data is provided under the program’s data-use policy to enable developers, researchers, artists, and the public to analyze Citi Bike behavior. The historical trip data is updated daily and includes information for each ride including ride ID, type of rideable, start and end latitude/longitude, user type, etc.

We downloaded the [JC Citi Bike Trip dataset](https://s3.amazonaws.com/tripdata/index.html) for the 2023 calender year, corresponding to 12 files dated 202301 through 202312.


#### Cleaning
The 12 monthly files are .csv files, so they were imported with `read_csv`. We encoded the data with the variable classes outlined by the Citi Bike data structure (e.g. `ride_id` variable was coded as a character instead of numeric). Then .csv files were merged into one dataset. Also, variable names were cleaned with `janitor::clean_names`. The initial dataset had `r nrow(citibike_2023)` observations and `r ncol(citibike_2023)` variables.

Then we reformatted and created new variables in our dataset for later analysis. We added the `ride_length_min` variable by subtracting the `ended_at` and `started_at` variable for each ride. Then we added the `time_of_day` variable and assigned a time of day category (i.e. Morning, Afternoon, Evening, or Night) based on the `start_hour` variable for each observation. We also added the `day_type` variable and assigned the type of day category (i.e. Weekday or Weekend) based on the `start_day` variable for each observation. The `rideable_type` variable was renamed to a clearer variable called `bike type` and names under this field were standardized into clearer categories (e.g. electric_bike renamed to Electric). We added the `season` variable and assigned a season category (i.e. Winter, Spring, Summer, or Fall) based on the `start_month` variable for each observation. Then we added the `ride_length_category` variable and assigned a ride length category based on the `ride_length_min` variable for each observation (e.g. `ride_length_min` less than 10 mins is classified as "Short (<10 min)"). Lastly, we added the `nj_area` variable and assigned a New Jersey area category based on longitude value (e.g. `nj_area` is "Jersey City" for areas where longitude less than 74.03).

We converted character variables (e.g. `member_type`) to factor where appropriate with ordering in mind. Also, all date and time variables were changed to standard data and time formatting.

Unnecessary data or problematic trips were filtered out such as rides shorter than one minute, rides lasting more than 24 hours, trips where the end time precedes the start time, and very short rides that began and ended at the same station.

The new and reformatted dataset has `r nrow(citibike_nj_analysis)` observations and `r ncol(citibike_nj_analysis)` variables.

To view more details about our data sources go to the [Data](data.html) tab.

## Exploratory Data Analysis
Overall, we wanted conduct a series of statistical analyses to quantify how member type, day of the week, and seasonal factors influence riding behavior. To understand which predictor and outcome variables would be important for our analysis we examined patterns in NJ Citi Bike usage. In our exploratory data analysis (EDA), we examined ridership in New Jersey City by monthly and seasonal patterns, by temporal patterns, by user type, and patterns in ride duration. 

To learn more about our exploratory data analysis go to the [EDA](EDA.html) tab.

## Analysis
In this data analysis, we test to see if there is evidence to conclude an association between member type, day of week, or season and riding behavior. First, a t-test comparing ride duration by member type revealed that casual riders take significantly longer trips than annual members, with an average difference of 8.68 minutes and a highly significant p-value (< 0.001, 95% CI: 8.49–8.87 minutes). Next, a chi-square test evaluated the relationship between member type and day type, showing a strong association (X² = 16,403.81, df = 1, p < 0.001), indicating that casual riders are disproportionately active on weekends compared to annual members. Finally, an ANOVA examined ride duration across seasons and found significant differences (F = 1,189, df = 3, p < 0.001), demonstrating that rides tend to be longer or shorter depending on the season.

To learn more about our data analysis go to the [Analysis](analysis.html) tab.

## Discussion

#### Key findings
The NJ Citi Bike system functions primarily as a commuter service, reflected in the fact that 74% of all rides are taken by annual members and that usage peaks during typical weekday commuting hours. These annual members generally take short, efficiency-focused trips, averaging 8.9 minutes, while casual riders exhibit a different pattern altogether, favoring longer, more leisurely weekend rides that average 17.6 minutes. Ridership also varies significantly with weather: summer produces roughly twice as many trips as winter, and ride duration tend to increase during warmer months. Even with electric bikes available, classic bikes overwhelmingly dominate system usage, accounting for 86.6% of all rides.

#### Limitations

#### Recommendations
* Target casual riders with weekend/leisure promotions
* Ensure sufficient classic bike availability (high demand)
* Consider weather-based pricing or promotions
* Focus maintenance/availability during weekday commute peaks
